### ISSUE TITLE
CollectionAustat: additional string as CanEd identification

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lilac#9]
The `Austat` should have an additional field that is the identifier of that element within a historical collection.
No, better: this number must be part of the Austat-Collection link, so from `CollectionSuper` (now `CollectionAustat`, see below)
That table already has a field `order`
It should also get a field `idno`

But: where to fill in this field??

**NOTE**:
I double-checked with the P.I. whether one Austat can only have one particular collection identification number. But this is not the case. An Austat can have multiple collection identification numbers, depending on which collection is inside in.
Implications: 
1. there should be an `idno` field in `CollectionSuper` >> is now `CollectionAustat`
2. there should be a way for the user to edit this `idno` field
    1. For instance, a details view for `CollectionAustat`
4. the contents of this field should be shown in the corresponding details and list views

**HOWEVER**:
The `Austat` already got some more identification. It now has a user-supplied `lilacode`, which combines with the `Auwork` it connects with. The combined Auwork + lilacode are a unique label for the Austat. This label uniquely sets it out in any historical collection, I would say.
Conclusion: perhaps no additional `idno` field in the CollectionAustat link table is needed (though that field **has** in fact been added, yet not made available for editing yet).

But see what happens after importing a number of canon witnesses and automatically adding Austats:
![image](https://user-images.githubusercontent.com/11887269/184150432-2c4c9bcf-c48a-4a67-8959-35e589621a06.png)

The resulting `Key` field clearly shows that there is a lot of ambiguity.

**Comment by ErwinKomen** [comment]
Update: corrected the `key` shown in the list above. It should be a combination of `Austat.auwork.key` + `Austat.keycode`

I had corrected this in `AustatListView.get_field_value()` (for `keycode`), but I've now also corrected it in model `Austat`, method `get_keycode()`

**Comment by Sgietus** [comment]
The _full_ key of a canon witness is the [KEY MANUSCRIPT].[HISTCOL].number. Right now, it takes the [KEY MANUSCRIPT] from the manuscript in which it is entered, but the [KEY HISTCOL] from the HISTCOL that is connected to the relevant AUSTAT. This is not logical, for an AUSTAT can occur in multiple HISTCOLs. A better solution would be either to 1) take the code from the COLWIT, or 2) from a CANED.

It makes more sense to _enter_ the HISTCOL in a CANWIT entry (not possible right now) rather than an AUSTAT entry (as it is now). The AUSTAT entry should generate a list of HISTCOLs is it found in.

**Comment by ErwinKomen** [comment]
Back to the original question for this issue #9: should a `CollectionAustat` contain an additional string?
The answer to that is: **YES**
And the reason is that each  `CollectionAustat` item from a historical collection must have its own `CanEd` (canon edition) key.
The `CanEd` key is built up of two components:
1. The short key (`lilacode`) of the Historical Collection (e.g. `Coll91`)
2. A **number** of this element within the Historical Collection

As for (2) above: it is not entirely clear whether that number can be determined automatically (the `order` number within a historical collection), or whether that number should be user-specifiable.
In the latter case, a details view of the `CollectionAustat` must be provided, where the user is able to edit this number.
Need to clarify this!

Right now the implementation is: **automatically determined** `CanEd` key, based on the Historical Collection `lilacode` + the order number of the item within the Historical collection.

**Comment by ErwinKomen** [comment]
> The _full_ key of a canon witness is the [KEY MANUSCRIPT].[HISTCOL].number. Right now, it takes the [KEY MANUSCRIPT] from the manuscript in which it is entered, but the [KEY HISTCOL] from the HISTCOL that is connected to the relevant AUSTAT. This is not logical, for an AUSTAT can occur in multiple HISTCOLs. A better solution would be either to 1) take the code from the COLWIT, or 2) from a CANED.
> 
> It makes more sense to _enter_ the HISTCOL in a CANWIT entry (not possible right now) rather than an AUSTAT entry (as it is now). The AUSTAT entry should generate a list of HISTCOLs is it found in.

I'm moving this to a separate issue about how lilacodes / keys should be determined / calculated. Issue #24

**Comment by ErwinKomen** [comment]
It has become clear for several reasons, that it is better to rename `CollectionAustat` into `Caned`.
1. Done the renaming
2. Added fields `ftext` and `ftrans`
3. Added a listview for `Caned`
4. Adding a details view for `Caned`
5.

**Comment by ErwinKomen** [comment]
All seems to work fine now!

**Comment by ErwinKomen** [comment]
Should be able to view and edit fields `ftext` and `ftrans`!!!

**Comment by ErwinKomen** [comment]
Okay, that is solved now. And they have been filled 'by default' (one time) with the ftext/ftrans from the Austat they are attached to.
